### ISSUE TITLE
Unable to login user from a different app

### ISSUE THREAD

**Issue by netlander** [mjhea0/passport-local#3]
After using your code I encountered an issue with passport local authentication policy where I have registered a user on one express site but when I try to login the same user from a different app/site it seems not possible.

Tried also creating a user in the second app with the same result, i.e. not able to authenticate the new user in the first express app.

Is this a feature or am I missing something?

**Comment by mjhea0** [comment]
What do you mean by a different app/site? You probably would want to use  tokens for this instead.

**Comment by netlander** [comment]
It's like I have two different deployments, completely different express apps based on your code as a starting point and wanted to have them pointing to the same database/schema etc... for authenticating the same list of users. That's where I got problems mentioned above.
Not sure I understand what you mean by "use tokens" but it sure looks like a limitation with passport-local-mongoose or some other middleware.
Any further pointers would be greatly appreciated
Thanks

**Comment by mjhea0** [comment]
Yes, I wouldn't use `passport-local-mongoose` in that case. Use this instead -> https://github.com/mjhea0/passport-testing
